feat: move to turborepo, init docs
frontzen/design-system pull request #1
Opened 2022-11-27 06:36 UTC by alisajadih

2022-11-27 08:57 UTC, mdeljavan commented on .husky/pre-commit
>  yarn lint-staged && \
```suggestion
yarn lint-staged
```

2022-11-27 08:57 UTC, mdeljavan commented on .husky/pre-commit
> +yarn type-check&& \
```suggestion
yarn type-check
```

2022-11-27 08:57 UTC, mdeljavan commented on apps/docs/package.json
> +    "lint": "eslint --max-warnings=0 \"**/*.{js,jsx,ts,tsx}\"",
```suggestion
    "lint": "yarn -T eslint --max-warnings=0 \"**/*.{js,jsx,ts,tsx}\"",
```

2022-11-27 08:57 UTC, mdeljavan commented on package.json
> +    "chromatic": "chromatic",
uninstall chromatic

2022-11-27 08:57 UTC, mdeljavan commented on package.json
> +    "@front.zen/design-system": "^0.0.1",
move to .storybook

2022-11-27 08:57 UTC, mdeljavan commented on libs/core/package.json
>        "default": "./src"
```suggestion
      "default": "./dist"
```

2022-11-27 08:57 UTC, mdeljavan commented on libs/core/package.json
> +  "types": "./src/index.ts"
check it

2022-11-27 10:23 UTC, alisajadih commented on .storybook/tsconfig.json
> +  "include": ["./*"]
it does not work

2022-11-28 10:05 UTC, alisajadih commented on turbo.json
> +      "outputs": ["dist/**"]
ack

2022-11-28 10:33 UTC, mdeljavan approved these changes

2022-11-28 11:13 UTC, alisajadih commented on .prettierignore
> +# See http://help.github.com/ignore-files/ for more about ignoring files.
i made a softlink

2022-11-28 11:28 UTC, mdeljavan approved these changes

2022-11-28 14:52 UTC, mdeljavan requested changes
why did you remove the .prettierignore file?

2022-11-29 06:30 UTC, mdeljavan approved these changes

2022-11-29 07:07 UTC, merged