Desktop wrapper
frontzen/design-system pull request #17
Opened 2022-12-19 06:45 UTC by XaviAlonsoo

2022-12-24 11:34 UTC, mdeljavan requested changes

2022-12-24 11:34 UTC, mdeljavan commented on libs/pickers/src/internals/hooks/useMaskedInput.ts
> +    const finalString = text === '' || text === mask ? '' : text;
```suggestion
    const finalString = text === mask ? '' : text;
```

2022-12-25 09:20 UTC, XaviAlonsoo commented on libs/pickers/src/internals/hooks/useMaskedInput.ts
> +  }, [acceptRegex, disableMaskedInput, inputFormat, mask, utils]);
I added default_regex to the functions, also we should inform the user to memo the acceptedRegex

2022-12-25 09:38 UTC, mdeljavan approved these changes

2022-12-25 09:39 UTC, merged