feat: Implement shadowing and spacing
frontzen/design-system pull request #20
Opened 2022-12-31 13:50 UTC by MahdiAbdi

customize shadows and use them in a storybook. set a new default spacing for the design system.
Closes #6

2022-12-31 13:54 UTC, alisajadih commented on libs/core/src/styles/constants.ts
> +  '0px 3px 3px -2px rgba(0,0,0,0.2),0px 3px 4px 0px rgba(0,0,0,0.14),0px 1px 8px 0px rgba(0,0,0,0.12)',
what are these?

2022-12-31 13:56 UTC, MahdiAbdi commented on libs/core/src/styles/constants.ts
> +  '0px 3px 3px -2px rgba(0,0,0,0.2),0px 3px 4px 0px rgba(0,0,0,0.14),0px 1px 8px 0px rgba(0,0,0,0.12)',
shadows from [MUI default theme](https://mui.com/material-ui/customization/default-theme/)

2022-12-31 14:02 UTC, alisajadih commented on libs/core/src/styles/constants.ts
> +  '0px 3px 3px -2px rgba(0,0,0,0.2),0px 3px 4px 0px rgba(0,0,0,0.14),0px 1px 8px 0px rgba(0,0,0,0.12)',
You don't need to copy them. 
shadows : [...theme.shadows , your shadows]

2022-12-31 14:04 UTC, MahdiAbdi commented on libs/core/src/styles/constants.ts
> +  '0px 3px 3px -2px rgba(0,0,0,0.2),0px 3px 4px 0px rgba(0,0,0,0.14),0px 1px 8px 0px rgba(0,0,0,0.12)',
The order makes difference. 
e.g: index 0 is default, 1 is custom, 2 is default, 3 is custom.

2022-12-31 14:05 UTC, MahdiAbdi commented on libs/core/src/styles/constants.ts
> +  '0px 3px 3px -2px rgba(0,0,0,0.2),0px 3px 4px 0px rgba(0,0,0,0.14),0px 1px 8px 0px rgba(0,0,0,0.12)',
unless I do something like this:
const shadows = theme.shadows;
shadows[1] = ...
shadows[24] =...

then export shadows;

2022-12-31 14:09 UTC, alisajadih commented on libs/core/src/styles/Shadow.stories.tsx
> +export default {
why we need extra folder? 
Core/shadows?

2022-12-31 14:09 UTC, alisajadih commented on libs/core/src/styles/constants.ts
> +export const spacing = 4;
you change the spacing. and buttons affected

2022-12-31 14:10 UTC, alisajadih commented on libs/core/src/styles/constants.ts
> +  '0px 3px 3px -2px rgba(0,0,0,0.2),0px 3px 4px 0px rgba(0,0,0,0.14),0px 1px 8px 0px rgba(0,0,0,0.12)',
it's better. if default shadows change, you don't need to change them all or track them.

2022-12-31 14:11 UTC, MahdiAbdi commented on libs/core/src/styles/constants.ts
> +  '0px 3px 3px -2px rgba(0,0,0,0.2),0px 3px 4px 0px rgba(0,0,0,0.14),0px 1px 8px 0px rgba(0,0,0,0.12)',
then another question rises. what if the number of custom items increased? 10 or 20 custom shadows? then the above method won't be a good idea.

2023-01-02 12:43 UTC, alisajadih commented on libs/core/src/styles/constants.ts
> +export const createShadows = (defaultShadows: Shadows): Shadows =>
filename

2023-01-02 12:43 UTC, alisajadih commented on libs/core/src/styles/createTheme.tsx
> +  const defaultTheme = createMuiTheme();
defaultMuiTheme

2023-01-02 12:53 UTC, mdeljavan requested changes

2023-01-02 12:53 UTC, mdeljavan commented on libs/core/src/styles/createTheme.tsx
> +  return createMuiTheme(createDefaultOptions(defaultTheme), options, ...args);
```suggestion
  const theme = createMuiTheme(createDefaultOptions(defaultTheme), options, ...args);
  theme.shadows = createShadows(theme.shadows);
  return theme
```

2023-01-02 12:53 UTC, mdeljavan commented on libs/core/src/styles/constants.ts
> +export const createShadows = (defaultShadows: Shadows): Shadows =>
IMO this function is util

2023-01-02 13:36 UTC, MahdiAbdi commented on libs/core/src/styles/constants.ts
> +export const createShadows = (defaultShadows: Shadows): Shadows =>
what do you think about the new change?
https://github.com/frontzen/design-system/pull/20/commits/bd4ddcdd5eb987f5ec3a0fbeb4b2b90727e397a3

2023-01-02 13:41 UTC, MahdiAbdi commented on libs/core/src/styles/createTheme.tsx
> +  return createMuiTheme(createDefaultOptions(defaultTheme), options, ...args);
I don't like this.
what if we decided to change some other styles and they needed the defaultMuiTheme.
adding them to createTheme function doesn't seem like a great idea.

2023-01-02 13:53 UTC, MahdiAbdi commented on libs/core/src/styles/createTheme.tsx
> +  return createMuiTheme(createDefaultOptions(defaultTheme), options, ...args);
fixed it.

2023-01-02 13:54 UTC, mdeljavan approved these changes

2023-01-03 07:01 UTC, alisajadih submitted a review, later dismissed

2023-01-11 11:34 UTC, mdeljavan approved these changes

2023-01-14 06:45 UTC, merged