feat: implement checkbox
frontzen/design-system pull request #21
Opened 2023-01-01 14:11 UTC by amirhossein-asadi

2023-01-02 12:34 UTC, mdeljavan requested changes

2023-01-02 12:34 UTC, mdeljavan commented on libs/core/src/styles/createTheme.tsx
> +import { Unselected } from '../checkbox/Icons/Unselected';
remove

2023-01-02 12:34 UTC, mdeljavan commented on libs/core/src/styles/createTheme.tsx
> +          },
remove these and override fontSize in MuiSvgIcon

2023-01-04 11:58 UTC, mdeljavan requested changes

2023-01-04 11:58 UTC, mdeljavan commented on libs/core/src/checkbox/Icons/Checked.tsx
> +    <SvgIcon {...props}>
set viewBox

2023-01-04 11:58 UTC, mdeljavan commented on libs/core/src/checkbox/checkbox.ts
> +      },
define svg font size in MuiSvgIcon component

2023-01-04 14:03 UTC, mdeljavan submitted a review, later dismissed

2023-01-07 06:02 UTC, alisajadih approved these changes

2023-01-07 06:25 UTC, mdeljavan approved these changes

2023-01-07 06:34 UTC, mdeljavan approved these changes

2023-01-07 06:36 UTC, merged